### PR TITLE
Fix: Bug Fixes

### LINKED ISSUE #26: Azure Firewall Basic does not create `AzureFirewallManagementSubnet`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.4.2

### Module Version

0.1.0

### AzureRM Provider Version

3.54

### Affected Resource(s)/Data Source(s)

azurerm_firewall

### Terraform Configuration Files

```hcl
Select basic sku
```

### tfvars variables values

```hcl
Select basic sku
```

### Debug Output/Panic Output

```shell
...
```

### Expected Behaviour

_No response_

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #46: Firewall does not accept ThreatIntelMode in current sku AZFW_Hub
### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.5.3

### Module Version

0.2.0

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_firewall.fw

### Terraform Configuration Files

```hcl
variable "tenant_id" {}
variable "subscription_id" {}
variable "location" {}

variable "proj" {}
variable "env" {}
variable "default_tags" {}

variable "vnet_hub_address_space" {}
variable "vnet_hub_routing_address_space" {}
variable "firewall_subnet_address_prefix" {}

resource "azurerm_resource_group" "network" {
  name     = module.naming-network.resource_group.name_unique
  location = var.location
  tags     = var.default_tags
}

module "naming-hub" {
  source  = "Azure/naming/azurerm"
  version = "~> 0.3"
  suffix  = ["${var.proj}", "${var.env}", "hub"]
}

module "naming-network" {
  source  = "Azure/naming/azurerm"
  version = "~> 0.3"
  suffix  = ["${var.proj}", "${var.env}", "network"]
}

module "hubnetworking" {
  source  = "Azure/hubnetworking/azurerm"
  version = "~> 0.2"

  hub_virtual_networks = {
    neu-hub = {
      name                            = module.naming-hub.virtual_network.name_unique
      location                        = azurerm_resource_group.network.location
      resource_group_name             = azurerm_resource_group.network.name
      resource_group_creation_enabled = false
      resource_group_lock_enabled     = false
      #mesh_peering_enabled            = true

      address_space         = var.vnet_hub_address_space
      routing_address_space = var.vnet_hub_routing_address_space
      firewall = {
        name              = module.naming-hub.firewall.name_unique
        sku_tier          = "Standard"
        sku_name          = "AZFW_Hub"
        threat_intel_mode = "Off"
        zones             = ["1", "2", "3"]
        default_ip_configuration = {
          public_ip_config = {
            name  = [module.naming-hub.public_ip.name_unique]
            zones = ["1", "2", "3"]
            tags  = var.default_tags
          }
        }
        subnet_address_prefix = var.firewall_subnet_address_prefix
        tags                  = var.default_tags
      }
      tags = var.default_tags
    }
  }
}

terraform {
  required_version = ">= 1.3"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.66"
    }
  }
}

provider "azurerm" {
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id

  features {
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
  }
}
```

### tfvars variables values

```hcl
tenant_id       = "f17ae016-64fd-452e-bbb1-XXXXX"
subscription_id = "9720b7c2-64c1-4038-bcfe-XXXXX"
location        = "northeurope"

# project
proj = "vpp"
env  = "nonprod"

default_tags = {
  "environment" : "nonprod",
  "project"     : "vpp",
}

vnet_hub_address_space         = ["10.100.0.0/16"]
vnet_hub_routing_address_space = ["10.100.0.0/16"]
firewall_subnet_address_prefix = "10.100.0.0/24"
```

### Debug Output/Panic Output

```shell
$ tf apply play.tfplan    
module.hubnetworking.module.hub_virtual_networks["neu-hub"].azurerm_virtual_network.vnet: Creating...
module.hubnetworking.module.hub_virtual_networks["neu-hub"].azurerm_virtual_network.vnet: Creation complete after 6s [id=/subscriptions/9720b7c2-64c1-4038-bcfe-XXXXXX/resourceGroups/rg-vpp-nonprod-network-ioym/providers/Microsoft.Network/virtualNetworks/vnet-vpp-nonprod-hub-txs9]
module.hubnetworking.azurerm_subnet.fw_subnet["neu-hub"]: Creating...
module.hubnetworking.azurerm_public_ip.fw_default_ip_configuration_pip["neu-hub"]: Creating...
module.hubnetworking.azurerm_public_ip.fw_default_ip_configuration_pip["neu-hub"]: Creation complete after 3s [id=/subscriptions/9720b7c2-64c1-4038-bcfe-XXXXXX/resourceGroups/rg-vpp-nonprod-network-ioym/providers/Microsoft.Network/publicIPAddresses/fw-vpp-nonprod-hub-txs9]
module.hubnetworking.azurerm_subnet.fw_subnet["neu-hub"]: Creation complete after 5s [id=/subscriptions/9720b7c2-64c1-4038-bcfe-XXXXXX/resourceGroups/rg-vpp-nonprod-network-ioym/providers/Microsoft.Network/virtualNetworks/vnet-vpp-nonprod-hub-txs9/subnets/AzureFirewallSubnet]
module.hubnetworking.azurerm_firewall.fw["neu-hub"]: Creating...
╷
│ Error: creating/updating Firewall: (Azure Firewall Name "fw-vpp-nonprod-hub-txs9" / Resource Group "rg-vpp-nonprod-network-ioym"):
network.AzureFirewallsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- 
Original Error: Code="AzureFirewallDoesNotAcceptThreatIntelModeInSku" 
Message="Azure Firewall /subscriptions/9720b7c2-64c1-4038-bcfe-XXXXXX/resourceGroups/rg-vpp-nonprod-network-ioym/providers/Microsoft.Network/azureFirewalls/fw-vpp-nonprod-hub-txs9 
does not accept ThreatIntelMode in current sku AZFW_Hub." Details=[]
│ 
│   with module.hubnetworking.azurerm_firewall.fw["neu-hub"],
│   on .terraform/modules/hubnetworking/main.tf line 158, in resource "azurerm_firewall" "fw":
│  158: resource "azurerm_firewall" "fw" {
```

### Expected Behaviour

It should be able to create firewall with SKU "AZFW_Hub".

### LINKED ISSUE #47: firewall: default_ip_configuration.public_ip_config.name is ignored
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.5.3

### Module Version

0.2.0

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_public_ip.fw_default_ip_configuration_pip

### Terraform Configuration Files

```hcl
variable "tenant_id" {}
variable "subscription_id" {}
variable "location" {}

variable "proj" {}
variable "env" {}
variable "default_tags" {}

variable "vnet_hub_address_space" {}
variable "vnet_hub_routing_address_space" {}
variable "firewall_subnet_address_prefix" {}

resource "azurerm_resource_group" "network" {
  name     = module.naming-network.resource_group.name_unique
  location = var.location
  tags     = var.default_tags
}

module "naming-hub" {
  source  = "Azure/naming/azurerm"
  version = "~> 0.3"
  suffix  = ["${var.proj}", "${var.env}", "hub"]
}

module "naming-network" {
  source  = "Azure/naming/azurerm"
  version = "~> 0.3"
  suffix  = ["${var.proj}", "${var.env}", "network"]
}

module "hubnetworking" {
  source  = "Azure/hubnetworking/azurerm"
  version = "~> 0.2"

  hub_virtual_networks = {
    neu-hub = {
      name                            = module.naming-hub.virtual_network.name_unique
      location                        = azurerm_resource_group.network.location
      resource_group_name             = azurerm_resource_group.network.name
      resource_group_creation_enabled = false
      resource_group_lock_enabled     = false
      #mesh_peering_enabled            = true

      address_space         = var.vnet_hub_address_space
      routing_address_space = var.vnet_hub_routing_address_space
      firewall = {
        name              = module.naming-hub.firewall.name_unique
        sku_tier          = "Standard"
        sku_name          = "AZFW_VNet"
        threat_intel_mode = "Off"
        zones             = ["1", "2", "3"]
        default_ip_configuration = {
          public_ip_config = {
            name  = [module.naming-hub.public_ip.name_unique]
            zones = ["1", "2", "3"]
            tags  = var.default_tags
          }
        }
        subnet_address_prefix = var.firewall_subnet_address_prefix
        tags                  = var.default_tags
      }
      tags = var.default_tags
    }
  }
}

terraform {
  required_version = ">= 1.3"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.66"
    }
  }
}

provider "azurerm" {
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id

  features {
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
  }
}
```

### tfvars variables values

```hcl
tenant_id       = "f17ae016-64fd-452e-bbb1-XXXXX"
subscription_id = "9720b7c2-64c1-4038-bcfe-XXXXX"
location        = "northeurope"

# project
proj = "vpp"
env  = "nonprod"

default_tags = {
  "environment" : "nonprod",
  "project"     : "vpp",
}

vnet_hub_address_space         = ["10.100.0.0/16"]
vnet_hub_routing_address_space = ["10.100.0.0/16"]
firewall_subnet_address_prefix = "10.100.0.0/24"
```

### Debug Output/Panic Output

```shell
no panic here after using SKU "AZFW_VNet"
```

### Expected Behaviour

It should have created a PIP with name `pip-vpp-nonprod-hub-txs9`.

### Actual Behaviour

It has used the same name as the firewall.

```
$ tf console
> module.naming-hub.firewall.name_unique
"fw-vpp-nonprod-hub-txs9"
> module.naming-hub.public_ip.name_unique
"pip-vpp-nonprod-hub-txs9"
```

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #48: NextHopIpAddress cannot be Null or Empty in route when NextHopType is VirtualAppliance
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.5.3

### Module Version

0.2.0

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network_peering.hub_peering

### Terraform Configuration Files

```hcl
variable "tenant_id" {}
variable "subscription_id" {}
variable "location" {}

variable "proj" {}
variable "env" {}
variable "default_tags" {}

variable "vnet_hub_address_space" {}
variable "vnet_hub_routing_address_space" {}
variable "firewall_subnet_address_prefix" {}
variable "vnet_aks_address_space" {}
variable "vnet_aks_routing_address_space" {}

resource "azurerm_resource_group" "core" {
  name     = module.naming-core.resource_group.name_unique
  location = var.location
  tags     = var.default_tags
}

resource "azurerm_resource_group" "network" {
  name     = module.naming-network.resource_group.name_unique
  location = var.location
  tags     = var.default_tags
}

module "naming-core" {
  source  = "Azure/naming/azurerm"
  version = "~> 0.3"
  suffix  = ["${var.proj}", "${var.env}", "core"]
}

module "naming-hub" {
  source  = "Azure/naming/azurerm"
  version = "~> 0.3"
  suffix  = ["${var.proj}", "${var.env}", "hub"]
}

module "naming-network" {
  source  = "Azure/naming/azurerm"
  version = "~> 0.3"
  suffix  = ["${var.proj}", "${var.env}", "network"]
}

module "hubnetworking" {
  source  = "Azure/hubnetworking/azurerm"
  version = "~> 0.2"

  hub_virtual_networks = {
    neu-hub = {
      name                            = module.naming-hub.virtual_network.name_unique
      location                        = azurerm_resource_group.network.location
      resource_group_name             = azurerm_resource_group.network.name
      resource_group_creation_enabled = false
      resource_group_lock_enabled     = false
      #mesh_peering_enabled            = true

      address_space         = var.vnet_hub_address_space
      routing_address_space = var.vnet_hub_routing_address_space
      firewall = {
        name              = module.naming-hub.firewall.name_unique
        sku_tier          = "Standard"
        sku_name          = "AZFW_VNet"
        threat_intel_mode = "Off"
        zones             = ["1", "2", "3"]
        default_ip_configuration = {
          public_ip_config = {
            name  = [module.naming-hub.public_ip.name_unique]
            zones = ["1", "2", "3"]
            tags  = var.default_tags
          }
        }
        subnet_address_prefix = var.firewall_subnet_address_prefix
        tags                  = var.default_tags
      }
      tags = var.default_tags
    }

    neu-aks = {
      name                            = module.naming-core.virtual_network.name_unique
      location                        = azurerm_resource_group.core.location
      resource_group_name             = azurerm_resource_group.core.name
      resource_group_creation_enabled = false
      resource_group_lock_enabled     = false
      mesh_peering_enabled            = true

      address_space         = var.vnet_aks_address_space
      routing_address_space = var.vnet_aks_routing_address_space
    }
  }
}

terraform {
  required_version = ">= 1.3"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.66"
    }
  }
}

provider "azurerm" {
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id

  features {
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
  }
}
```

### tfvars variables values

```hcl
tenant_id       = "f17ae016-64fd-452e-bbb1-XXXXX"
subscription_id = "9720b7c2-64c1-4038-bcfe-XXXXX"
location        = "northeurope"

# project
proj = "vpp"
env  = "nonprod"

default_tags = {
  "environment" : "nonprod",
  "project"     : "vpp",
}

vnet_hub_address_space         = ["10.100.0.0/16"]
vnet_hub_routing_address_space = ["10.100.0.0/16"]
firewall_subnet_address_prefix = "10.100.0.0/24"

vnet_aks_address_space         = ["10.110.0.0/16"]
vnet_aks_routing_address_space = ["10.110.0.0/16"]
```

### Debug Output/Panic Output

```shell
module.hubnetworking.azurerm_virtual_network_peering.hub_peering["vnet-vpp-nonprod-core-mcfe-vnet-vpp-nonprod-hub-txs9"]:
Creation complete after 53s [id=/subscriptions/9720b7c2-64c1-4038-bcfe-XXXXXX/resourceGroups/rg-vpp-nonprod-core-mcfe/providers/Microsoft.Network/virtualNetworks/vnet-vpp-nonprod-core-mcfe/virtualNetworkPeerings/vnet-vpp-nonprod-core-mcfe-vnet-vpp-nonprod-hub-txs9]
╷
│ Error: creating/updating Route Table (Subscription: "9720b7c2-64c1-4038-bcfe-XXXXXX"
│ Resource Group Name: "rg-vpp-nonprod-network-ioym"
│ Route Table Name: "neu-hub-rt"): performing CreateOrUpdate: unexpected status 400 with error:
MissingNextHopIpAddress: NextHopIpAddress cannot be Null or Empty in route neu-aks-10.110.0.0-16 when NextHopType is VirtualAppliance.
│ 
│   with module.hubnetworking.azurerm_route_table.hub_routing["neu-hub"],
│   on .terraform/modules/hubnetworking/main.tf line 71, in resource "azurerm_route_table" "hub_routing":
│   71: resource "azurerm_route_table" "hub_routing" {
│
```

### Expected Behaviour

It should have obtained the NextHopIpAddress and use if in the routing table.

### Actual Behaviour

Incomplete route definition.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #50: The name value from the `virtual_networks` output gives the map key as opposed to the name of the VNET.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.5.1

### Module Version

0.2.0

### AzureRM Provider Version

3.66

### Affected Resource(s)/Data Source(s)

output virtual_networks

### Terraform Configuration Files

```hcl
module "hubnetworks" {
  source  = "Azure/hubnetworking/azurerm"
  version = "0.2.0"

  hub_virtual_networks = {
    hub = {
      name                            = "vnet-hub"
      address_space                   = ["10.0.0.0/24"]
      resource_group_name             = "rg-hub"
      location                        = "uksouth"
      mesh_peering_enabled            = false
      resource_group_lock_enabled     = false
      subnets = {
        hub-vm = {
          name             = "default"
          address_prefixes = ["10.0.0.16/28"]
        }
      }
    }
  }
}

output "vnet_name" {
value = module.hubnetworks.virtual_networks["hub"].name
}
```

### tfvars variables values

```hcl
n\a
```

### Debug Output/Panic Output

```shell
n\a
```

### Expected Behaviour

the value of the output `vnet_name` to be `vnet-hub`

### Actual Behaviour

the value of the output `vnet_name` is `hub`

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by luke-taylor**
## Describe your changes
Addresses the following bugs: 
https://github.com/Azure/terraform-azurerm-hubnetworking/issues/26
https://github.com/Azure/terraform-azurerm-hubnetworking/issues/46
https://github.com/Azure/terraform-azurerm-hubnetworking/issues/47
https://github.com/Azure/terraform-azurerm-hubnetworking/issues/48
https://github.com/Azure/terraform-azurerm-hubnetworking/issues/50
## Issue number
Fixes #26, fixes #46, fixes #47, fixes #48, fixes #50 

## Checklist before requesting a review
- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [x] I have executed pre-commit on my machine
- [x] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by lonegunmanb** [comment]
Hi @luke-taylor thank you for the immense effort you've put into this pull request and your dedication to resolving these issues. Your hard work is truly appreciated.

I understand that you've already invested a lot of time and energy into this pull request. So, I will take the time to thoroughly review it this time around, despite its size.

However, for future reference, I would like to kindly suggest breaking down your pull requests into smaller ones, each corresponding to a single issue. This approach would simplify the review process and expedite the merging of changes.

Since this pr broke the unit test and its related to multiple issues, I have one question:

You've changed line 89 in `locals.tf` file from `next_hop_ip_address = try(local.firewall_private_ip[k_dst], v_src.hub_router_ip_address)` to `next_hop_ip_address = try(local.firewall_private_ip[k_dst], v_dst.hub_router_ip_address)`, may I ask why?

**Comment by luke-taylor** [comment]
> Hi @luke-taylor thank you for the immense effort you've put into this pull request and your dedication to resolving these issues. Your hard work is truly appreciated.
> 
> I understand that you've already invested a lot of time and energy into this pull request. So, I will take the time to thoroughly review it this time around, despite its size.
> 
> However, for future reference, I would like to kindly suggest breaking down your pull requests into smaller ones, each corresponding to a single issue. This approach would simplify the review process and expedite the merging of changes.
> 
> Since this pr broke the unit test and its related to multiple issues, I have one question:
> 
> You've changed line 89 in `locals.tf` file from `next_hop_ip_address = try(local.firewall_private_ip[k_dst], v_src.hub_router_ip_address)` to `next_hop_ip_address = try(local.firewall_private_ip[k_dst], v_dst.hub_router_ip_address)`, may I ask why?

Hey @lonegunmanb, that's my bad I'll definitely do that in the future, apologies! 

The change is so that, that routing addresses are added as routes to every other vnet that's peered to ensure inter-vnet traffic always passes the firewalls/hub routers in each vnet.

**Comment by lonegunmanb** [comment]
Thanks for the justification, make sense to me! @luke-taylor

**Comment by luke-taylor** [comment]
@lonegunmanb, @matt-FFFFFF  Updating this code required a few modifications to the unit testing, would you mind double checking the unit test code?

**Review by lonegunmanb — APPROVED** [review]
LGTM but I'd like to let @matt-FFFFFF make the call.

**Review by matt-FFFFFF — APPROVED** [review]
LGTM - great work @luke-taylor

**Comment by rodmhgl** [comment]
> The change is so that, routing addresses are added as routes to every other vnet that's peered to ensure inter-vnet traffic always passes the firewalls/hub routers in each vnet.

This has the side effect of causing a crash when attempting to create an AzureBastionSubnet (as it doesn't support route tables) (or perhaps this is caused by another piece of the code?). 

I'm currently handling this by creating the AzureBastionSubnet outside of the module, but is this something that is easily bypassed?

**Comment by matt-FFFFFF** [comment]
Hi @rodmhgl 

Have you tried turning off the assign_generated_route_table for that subnet?

**Comment by rodmhgl** [comment]
Hey @matt-FFFFFF, that took care of the issue. Thanks for the help, appreciate you responding!

**Pull request merged**
