### PR TITLE
Fix typo in `management_ip_configuration`

### PR DESCRIPTION
**Pull request by SvenAelterman**
## Describe your changes

Fix `management_ip_coniguration` to `management_ip_configuration` so that `zones`, `ip_version`, and `sku_tier` are correctly processed.

## Issue number

#78 

## Checklist before requesting a review

- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [ ] I have passed pr-check on my machine

Thanks for your cooperation!

### CODE REVIEW

**Comment by SvenAelterman** [comment]
I realize the prepr-check fails, but I didn't touch those lines of code. If required, I can try to see if I can change the use of the `lookup` to be compliant with the check.

**Review by matt-FFFFFF — APPROVED** [review]

**Comment by matt-FFFFFF** [comment]
Thanks for the PR!

**Comment by SvenAelterman** [comment]
@matt-FFFFFF When will a new version with this fix be released?

**Comment by cpinotossi** [comment]
Did verify .terraform\modules\hubnetworking\locals.tf and the typo still exist:

  fw_management_ip_configuration_pip = {
    for k, v in var.hub_virtual_networks : k => {
      location            = local.virtual_networks_modules[k].vnet_location
      name                = try(v.firewall.management_ip_configuration.public_ip_config.name, "pip-afw-mgmt-${k}")
      resource_group_name = v.resource_group_name
      ip_version          = try(v.firewall.management_ip_coniguration.public_ip_config.ip_version, "IPv4")
      sku_tier            = try(v.firewall.management_ip_coniguration.public_ip_config.sku_tier, "Regional")
      zones               = try(v.firewall.management_ip_coniguration.public_ip_config.zones, null)
    } if try(v.firewall.sku_tier, "FirewallNull") == "Basic" && v.firewall != null
  }

Would be great if somebody could fix this typo so I can deploy an Basic FW.

**Comment by SvenAelterman** [comment]
@matt-FFFFFF Can you check into this again, please? Seems like the PR content was somehow reversed.

**Pull request merged**
